In [5]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} is barking........")

    def info(self):
        print(f"{self.name} is a {self.breed}")


german_shepherd = Dog("Rex", "German Shepherd")
german_shepherd.bark()
german_shepherd.info()

Rex is barking........
Rex is a German Shepherd


In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [5]:
a = torch.empty(2,3)
a

tensor([[-6.8058e-28,  4.3082e-41, -6.8058e-28],
        [ 4.3082e-41,  0.0000e+00,  0.0000e+00]])

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Every value is random, between 0 and 1. This is how we'll initialize neural network weights later.**

In [10]:
torch.rand(2,4)

tensor([[0.0617, 0.3146, 0.2753, 0.1385],
        [0.2720, 0.8580, 0.0919, 0.7893]])